//go:build integration

package sqlstore_test

import (
	"context"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/stretchr/testify/require"

	"github.com/galt-tr/go-arcade-toolbox/internal/testenv"
	"github.com/galt-tr/go-arcade-toolbox/pkg/utxostore"
	"github.com/galt-tr/go-arcade-toolbox/pkg/utxostore/sqlstore"
	"github.com/galt-tr/go-arcade-toolbox/pkg/utxostore/utxostoretest"
)

// newPostgresStore opens a migrated store on a fresh isolated schema of pg and
// registers its teardown.
func newPostgresStore(t *testing.T, pg *testenv.PostgresContainer, opts ...sqlstore.Option) *sqlstore.Store {
	t.Helper()
	dsn := pg.IsolatedSchemaDSN(t)
	s, err := sqlstore.OpenPostgres(context.Background(), dsn, opts...)
	require.NoError(t, err)
	t.Cleanup(func() { _ = s.Close(context.Background()) })
	return s
}

// TestSQLStore_Postgres runs the full conformance suite against PostgreSQL,
// one isolated schema per subtest, with exact selection and deterministic-clock
// timestamp subtests. Skips gracefully when no container runtime is available.
func TestSQLStore_Postgres(t *testing.T) {
	pg := testenv.StartPostgres(t)

	newStore := func(t *testing.T) utxostore.Store {
		return newPostgresStore(t, pg)
	}
	newStoreClock := func(t *testing.T) (utxostore.Store, utxostoretest.AdvanceFunc) {
		clk := &manualClock{t: baseTime}
		return newPostgresStore(t, pg, sqlstore.WithClock(clk.now)), clk.advance
	}

	utxostoretest.RunStoreSuite(t, newStore,
		utxostoretest.WithExactSelection(),
		utxostoretest.WithManualClock(newStoreClock),
	)
}

// seedUTXOsPostgres bulk-loads n equal-value claimable rows via pgx COPY,
// which is dramatically faster than row-by-row inserts for the 250k pool. seq
// is generated by the IDENTITY column, so it is not supplied.
func seedUTXOsPostgres(tb testing.TB, s *sqlstore.Store, sc utxostore.Scope, sats uint64, n int) {
	tb.Helper()
	ctx := context.Background()

	conn, err := s.DB().Conn(ctx)
	require.NoError(tb, err)
	defer func() { _ = conn.Close() }()

	err = conn.Raw(func(dc any) error {
		pgxConn := dc.(*stdlib.Conn).Conn()
		rows := make([][]any, n)
		for i := 0; i < n; i++ {
			rows[i] = []any{
				txidOf(i), int32(0), sc.UserID, sc.Basket,
				int16(sc.Tier), int64(sats), int32(107), baseTime,
			}
		}
		_, cErr := pgxConn.CopyFrom(ctx,
			pgx.Identifier{"utxos"},
			[]string{"txid", "vout", "user_id", "basket", "tier", "satoshis", "input_size", "created_at"},
			pgx.CopyFromRows(rows),
		)
		return cErr
	})
	require.NoError(tb, err)
}
